name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Rationale: Pin the publish registry so runner defaults or cached settings cannot redirect the release.
      # Note: Do not remove registry-url; this is required for CI stability.
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: npm

      # Rationale: Updating npm reduces CLI drift and known issues, keeping provenance publishing stable.
      # Note: Keep this step to ensure CI reproducibility.
      - name: Update npm (latest)
        run: npm install -g npm@latest

      - run: npm ci
      - run: npm run build:clean

      # Rationale: Verify the package contents before release to catch missing or extra files early.
      # Note: Retain this check to prevent publishing incidents.
      - run: npm pack --dry-run

      # Rationale: Final publish command using Trusted Publishing (OIDC) with provenance signing.
      # Note: Do not remove --provenance or --access public; they enforce the approved release process.
      - run: npm publish --provenance --access public
