name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 理由: npm の公開先レジストリを明示して Runner 既定やキャッシュの影響を排除し、常に npmjs 本番を使うため。
      # 注意: この指定（registry-url）は削除しないこと（CI 安定化に必須）。
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: npm

      # 理由: provenance 署名付き公開の安定化のため、npm CLI の挙動差/既知不具合を回避する（認証周りの差異を抑制）。
      # 注意: この行は削除しないこと（CI 安定化・再現性確保のため必須）。
      - name: Update npm (latest)
        run: npm install -g npm@latest

      - run: npm ci
      - run: npm run build:clean

      # 理由: 公開前に同梱物を検証し、意図しないファイル混入や欠落を早期検知するため。
      # 注意: この確認は削除しないこと（公開事故防止）。
      - run: npm pack --dry-run

      # 理由: Trusted Publishing（OIDC）で provenance 署名つき公開を実施する本番コマンド。
      # 注意: フラグ（--provenance / --access public）は削除しないこと（公開方式の一貫性維持）。
      - run: npm publish --provenance --access public
